name: video_player_plus
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Tizen.
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: VideoPlayerTizenPlugin
        fileName: video_player_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  video_player_plus_platform_interface:
    git:
      url: git@github.sec.samsung.net:f-project/video_player_plus_platform_interface.git
      ref: eca02d4f3131b628577577520f8a02ad962263e0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  pigeon: ^0.1.21
