name: video_player_plus
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Tizen.
version: 1.1.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: VideoPlayerTizenPlugin
        fileName: video_player_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  video_player_platform_interface: ^4.2.0
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint. The exact value doesn't matter since
  # the constraints on the interface pins it.
  # TODO(amirh): Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web: ^2.0.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  pigeon: ^0.1.21
